server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    # Отдача статики
    location / {
        try_files $uri $uri/ =404;
    }
    
    # Healthcheck
    location /health {
        return 200 'healthy\n';
        add_header Content-Type text/plain;
    }
    
    # Имитация основного API
    location /api/v1/status {
        return 200 '{"app": "emulator", "status": "ok"}';
        add_header Content-Type application/json;
    }
}
