apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "test-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "test-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}