replicaCount: 1

image:
  repository: registry.103.76.54.202.nip.io/netology/test-app
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: gitlab-registry

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: test-app.103.76.54.202.nip.io

nameOverride: ""
fullnameOverride: ""

